### ISSUE TITLE
As a NOI Facility manager I want a list view for all Location in order to have a quick overview of all Location at NOI Techpark.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.epaper.webapp#44]
The list view must create one row for each Location that shows at least:
- [x] the name of the location;
- [x] the room of the location.

Options should be:
- [x] an edit button
- [x] a delete button
- [x] a create button

**Comment by SaimonasFOS** [comment]
This task goes together with https://github.com/noi-techpark/it.bz.opendatahub.epaper.webapp/issues/43

**Comment by Piiit** [comment]
@SaimonasFOS Yes, I think it is nearly a duplicate, so lets continue all discussions on #43
