### ISSUE TITLE
As NOI secretary, I want to have different templates and forms to assign different designs to different e-display locations (like offices, meeting rooms, sign posts)

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.epaper.webapp#53]
Each template must contain the following information:
- [x] a human readable name that allows the user to choose the right template;
- [x] a human readable description that allows the user to explain how, when and where use the template;
- [x] a background image that the user can choose from an existing library or manually upload;
> manual upload works, library see --> #70 (postponed)
- [x] one or more text field. For each text field the user has to choose the type between:
  - [x] room (automatically filled from Open Data Hub APIs)
  - [x] event name (automatically filled from Open Data Hub APIs)
  - [x] event start (automatically filled from Open Data Hub APIs)
  - [x] event end (automatically filled from Open Data Hub APIs)
  - [x] string (manual input by the user).

Ideally the user should be able to position the text field by using the drag and drop on the template preview.

The template detail view must include also a preview that allows the user to see an example of the content that can be generated by using the template.

Link to useful APIS:
- Rooms: https://mobility.api.opendatahub.bz.it/v2/flat/NOI-Place/ 
- NOI Events: https://api.tourism.testingmachine.eu/swagger/index.html#/EventShort

**UPDATE**
- [x] #70
> postponed
- [x] #69
> postponed
- [x] Question: Do we need to already consider the resolution, bit and dpi of the image as defined below... should that be a drop-down or something in the template section or do we resize at backend?
> Can be found inside "Edit display" not needed for templates which get resized automatically

**Comment by AlePanTS** [comment]
**FORMAT**
Bitmap: Windows BMP (not Adobe BMP)

**BIT**
24 bit

**RESOLUTION**
1440(w) x 2560(h)

**DPI**
150

**Comment by AlePanTS** [comment]
# SMALL DISPLAY (7.8" EPD)
**FORMAT**
Bitmap: Windows BMP (not Adobe BMP)

**BIT**
1-24 bit

**RESOLUTION**
1872(w) x 1404(h)

**DPI**
150

**Comment by SaimonasFOS** [comment]
@AlePanTS Small question, can these displays show greyscale images? Or they only show black and white?

**Comment by AlePanTS** [comment]
@SaimonasFOS sure, both displays show grayscale image, it depends on the bits of the image:
- the large display show 24-bit image, this means there are no problems with grayscale images.
- the small display can show basically every image regardless of the bit, but 1 bit image will be a b/w image; in order to have a grayscale image it is necessary to increase the bits (for example a 4 bit image will result in 16 gray levels, and so on...)

**Comment by SaimonasFOS** [comment]
@AlePanTS Thanks.
Based on your information I think that the small display should not take 24 bit image since downloading it would take a lot of energy. But if it can show greyscale then 1 bit is not sufficient either. 
I think images for small displays should be 8 bit (256 grey levels if I'm correct).
What do you think?

**Comment by AlePanTS** [comment]
@SaimonasFOS I agree on 8 bit, but considering the kind of information that we are going to show (in the case of small display basically text), we could go down until 4 bit. In this case the choice has to be made in relation to the kind of image we are going to show; for my experience, even with 4 bit you can get excellent result.

**Comment by SaimonasFOS** [comment]
@AlePanTS Testing machine is updated so you can now test the image retrieval from API. I uploaded an example template with picture.

Call GET request to this adress: https://api.epaper.opendatahub.testingmachine.eu/template/getImage/75a0ad39-9761-4e44-93d7-529dbf104abe?convertToBMP=true&withTextFields=true

This request should return you a 24bit BMP image. Keep in mind that the request response format is "application/octet-stream" which is essentially a binary file without extension. The received file should be a valid image, it's just missing the "BMP" extension at the end.
Please test this and let me know if it works. If not, maybe I could try making the response format to be "image/bmp" but generally there should not be any difference.

**Comment by Piiit** [comment]
@SaimonasFOS I think that the response format should correspond to the real file in the future, so that it is then also testable in a browser... however for now the octet-stream is good enough if @AlePanTS gives the OK

**Comment by AlePanTS** [comment]
Thanks @SaimonasFOS, the image downloaded is fine and it is not a problem for me adding the .bmp extension at the end in order to make it work properly. @Piiit I confirm that octet-stream at the moment is not an issue to handle.

**Comment by Piiit** [comment]
@AlePanTS @SaimonasFOS Perfect, so lets go with octet-stream for now... I will open a to-do for the real mimetype

**Comment by Piiit** [comment]
@giovannigiannotta @SaimonasFOS @AlePanTS See UPDATE section in main comment

**Comment by SaimonasFOS** [comment]
@Piiit 

> a background image that the user can choose from an existing library is missing

Ok, I missed this one but maybe it is not a priority? Also it is unclear what kind of library would that be, would it be managed inside eInk webapp as well?

> we should start the add template with an empty white image to have immediately a preview

Yes, but for that the image size needs to be known in advance. Maybe I should've added display resolution field to template form.

> Question: Do we need to already consider the resolution, bit and dpi of the image as defined below... should that be a drop-down or something in the template section or do we resize at backend?

Bits and DPI as well as image format doesn't matter. The back-end converts received image to monochrome and uploads the image as PNG to bucket. When retrieving the image, it converts to PNG for webapp and BMP for displays. 
For size, there is currently no validation and the back-end doesn't resize the image. Again, maybe a resolution property is needed for Templates.
