### ISSUE TITLE
In the detail view of displays: show VPN certification expiration date

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.epaper.webapp#74]
This is only an API field and little UI update... It is not about alerting, which is another issue --> https://github.com/noi-techpark/it.bz.opendatahub.epaper.api/issues/41

**Comment by SaimonasFOS** [comment]
@Piiit is this required for current MVP? We never discussed about how it should work. Does the display send it's VPN expiration date with sync-status, or user should be able to set it in display add/edit form?

**Comment by sseppi** [comment]
> @sseppi Lets move it to MVP2?

Fine for me.
