### ISSUE TITLE
Multilingual events

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.epaper.webapp#91]
As ePaper content manager I want to be able to show the title of an event in all languages available (IT/DE/EN).

A possible solution could be, in case there is a title on different languages, concatenate the title of the event by inserting a new line for each language.

**Comment by sseppi** [comment]
@SaimonasFOS if I understand well, since in case a language is missing the field is populated with another default language, your proposal is to add 3 different field type:
-  "Event description (EN)"
- "Event description (IT)"
- "Event description (DE)"

Did I understood well?
In this case I see the problem that every time there is a multilingual event our Meeting Management Team has to change the template.

Another solution cold be to check if the texts are different concatenate it otherwise keep only the default one. Would it be possible?

@RudiThoeni can you tell us which language is the default óne?

**Comment by RudiThoeni** [comment]
There are already the fields
`
EventDescriptionDE
EventDescriptionIT
EventDescriptionEN
`
which is the title of the Event (bad naming i know, this comes from the interface where the data is synced)
The rule at the moment is default German,  when IT + EN does not have a title the german title is inserted in the field.....

The real text of the Event (which is not very often provided) is stored in this fields
`
EventTextDE
EventTextIT
EventTextEN
`
cheers
Rudi

**Comment by SaimonasFOS** [comment]
> In this case I see the problem that every time there is a multilingual event our Meeting Management Team has to change the template.

@sseppi That is a valid concern. I guess my proposed solution is not quite fitting then.

> Another solution cold be to check if the texts are different concatenate it otherwise keep only the default one. Would it be possible?

Yes, it would be possible. But with current API data texts will never be different. To give you an example how it looks right now:

        "EventDescription": {
            "de": "Workshop Vitalpina Hotels",
            "it": "Workshop Vitalpina Hotels",
            "en": "Workshop Vitalpina Hotels"
        },


        "EventDescription": {
            "de": "Visita guidata",
            "it": "Visita guidata",
            "en": "Visita guidata"
        },

        "EventDescription": {
            "de": "LVH – Erster Nachhaltigkeitslehrgang für KMU in Südtirol",
            "it": "LVH – Erster Nachhaltigkeitslehrgang für KMU in Südtirol",
            "en": "LVH – Erster Nachhaltigkeitslehrgang für KMU in Südtirol"
        },

These are 3 different events and their titles are the same in all 3 languages. And from what I see this is the case for all returned events, I could not find any example where event description would be translated.
So, I could implement the duplicate check that you are proposing but with the current state of Open Data Hub it would not be different from the current functionality of eInk back-end where I just take the English description. It would only be useful in the future if event descriptions would be different.

**Comment by sseppi** [comment]
> 
> > Another solution cold be to check if the texts are different concatenate it otherwise keep only the default one. Would it be possible?
> 
> Yes, it would be possible. But with current API data texts will never be different. To give you an example how it looks right now:
> 
> ```
>     "EventDescription": {
>         "de": "Workshop Vitalpina Hotels",
>         "it": "Workshop Vitalpina Hotels",
>         "en": "Workshop Vitalpina Hotels"
>     },
> 
> 
>     "EventDescription": {
>         "de": "Visita guidata",
>         "it": "Visita guidata",
>         "en": "Visita guidata"
>     },
> 
>     "EventDescription": {
>         "de": "LVH – Erster Nachhaltigkeitslehrgang für KMU in Südtirol",
>         "it": "LVH – Erster Nachhaltigkeitslehrgang für KMU in Südtirol",
>         "en": "LVH – Erster Nachhaltigkeitslehrgang für KMU in Südtirol"
>     },
> ```
> 
> These are 3 different events and their titles are the same in all 3 languages. And from what I see this is the case for all returned events, I could not find any example where event description would be translated. So, I could implement the duplicate check that you are proposing but with the current state of Open Data Hub it would not be different from the current functionality of eInk back-end where I just take the English description. It would only be useful in the future if event descriptions would be different.

@SaimonasFOS I think that at the moment we do not have any multilingual event planned so for this reason all languages are the same. In case we have a multilingual event with different titles in different languages the `EventDescription` won't be the same in the different languages. Just for example the `EventDescription` of a multilingual guided tour will be:

`
 "EventDescription": {
>         "de": "Führung",
>         "it": "Visita guidata",
>         "en": "Guided Tour"
>     },
`

**Comment by SaimonasFOS** [comment]
@sseppi Ok, thank you, I can see this event and it is going to be helpful.

Now, to recap, in case event descriptions are different, I have to write them in separate lines? Like this:

Führung
Visita guidata
Guided Tour

Do I understand this correctly? What should happen if there is not enough space for 3 lines, just write title in one language or add three dots like proposed here: https://github.com/noi-techpark/it.bz.opendatahub.epaper.webapp/issues/88 ?

If my example is incorrect, please give an example how the field text should look like.

**Comment by sseppi** [comment]
Yes, I think that write the different languages in different lines is the way to go for this MVP.

In case there is no enough space I would add the three dots in order to let the template editor understand that more space is needed.
