### ISSUE TITLE
Last changes for MVP1 after testing

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.epaper.webapp#98]
While we were testing with our meeting management department, it emerged the following things to be fixed before going on production:
- [x] start to show every event on the display 30 minutes before the start time
- [x] when there are no event in the room change the default message from "No current event" to "Welcome at NOI Techpark"
- [x] in the date add a space between the date and the pipe
- [x] add the possibility to set the width of a field or a margin in order to avoid that some pixels are hidden by the frame (see image below)
- [x] Do we still need the two proxy implementations? Eventually remove the proxy code and related README parts inside the [API](https://github.com/noi-techpark/it.bz.opendatahub.epaper.api)

----

![PXL_20220412_142304788](https://user-images.githubusercontent.com/7909989/163000457-f50d2891-4b09-4a15-9294-75343bb016bb.jpg)

**Comment by SaimonasFOS** [comment]
https://github.com/noi-techpark/it.bz.opendatahub.epaper.webapp/pull/99
https://github.com/noi-techpark/it.bz.opendatahub.epaper.api/pull/46

@sseppi Opened pull requests for this issue, informing you as you requested.
After merging, check display and template images. Make sure that image field width values are correct size!

**Comment by sseppi** [comment]
@SaimonasFOS ok super! Many thanks..
As soon as I will be able to test everything I will come back to you.
